before_script:
  - poetry install

stages:
  - check
  - deploy

lint:
  stage: check
  tags: [linux]
  script:
    - export PATH=$HOME/.rbenv/versions/2.7.1/bin:$PATH
    - poetry run python run-ci.py lint

check/linux/2.6:
  stage: check
  when: manual
  tags: [linux]
  script:
    - export PATH=$HOME/.rbenv/versions/2.6.6/bin:$PATH
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile gcc8-release-shared

check/linux/2.7:
  stage: check
  when: manual
  tags: [linux]
  script:
    - export PATH=$HOME/.rbenv/versions/2.7.1/bin:$PATH
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile gcc8-release-shared

check/linux/deployed/2.6:
  stage: check
  when: manual
  tags: [linux]
  script:
    - export PATH=$HOME/.rbenv/versions/2.6.6/bin:$PATH
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --profile gcc8-release-shared
  artifacts:
    paths:
      - vendor/libctanker/

check/linux/deployed/2.7:
  stage: check
  when: manual
  tags: [linux]
  script:
    - export PATH=$HOME/.rbenv/versions/2.7.1/bin:$PATH
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --profile gcc8-release-shared

check/macos:
  variables:
    RBENV_VERSION: 2.7.1
  stage: check
  when: manual
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile macos-release-shared

check/macos/deployed:
  variables:
    RBENV_VERSION: 2.7.1
  stage: check
  when: manual
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --profile macos-release-shared
  artifacts:
    paths:
      - vendor/libctanker/

nightly/linux:
  stage: check
  only:
    - schedules
  tags: [linux]
  script:
    - export PATH=$HOME/.rbenv/versions/2.6.6/bin:$PATH
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile gcc8-release-shared

nightly/macos:
  variables:
    RBENV_VERSION: 2.7.1
  stage: check
  only:
    - schedules
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile macos-release-shared

deploy:
  stage: deploy
  when: manual
  only:
    - tags
  tags: [linux]
  script:
    - export PATH=$HOME/.rbenv/versions/2.6.6/bin:$PATH
    - poetry run python run-ci.py deploy

mirror:
  tags:
    - linux
  stage: deploy
  only:
    # mirror public tags, releases branches
    # feature branches, and master
    - /\Av[0-9.]+\z/
    - master
    - /\Arelease/.*\z/
    - /\Afeat\/.+\z/   # feat/ branches
  except:
    - schedules
  script:
    - poetry run python run-ci.py mirror
