include:
  project: TankerHQ/gitlab-ci-files
  ref: 2022-08-19-248
  file: /common.yml

############
# Workflow #
############

workflow:
  rules:
    # web pipelines for releases only
    - if: $CI_PIPELINE_SOURCE == "web" && $SDK_RUBY_RELEASE_VERSION !~ /\A\d+\.\d+\.\d+(\.(alpha|beta)\.\d+)?\z/
      when: never
    - if: !reference [.if-invalid-native-conan-reference, if]
      when: never
    # allow everything else
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        CONAN_REMOTE: "artifactory"
    - if: $CI_COMMIT_REF_NAME =~ /\Arelease\/.+\z/
      variables:
        CONAN_REMOTE: "artifactory"
    - if: '$CI_MERGE_REQUEST_TITLE =~ /.*\[preview].*/'
      variables:
        CONAN_REMOTE: "artifactory-preview"
    - when: always
      variables:
        CONAN_REMOTE: "artifactory-staging"


###########
# Default #
###########

default:
  before_script:
    - poetry run python -m pip install --upgrade pip
    - poetry install
  image: registry.gitlab.com/tankerhq/docker/sdk-ruby:latest

##########
# Stages #
##########

stages:
  - lint
  - prepare
  - check
  - deploy

#############################
# Default settings override #
#############################

.before-script/download-artifacts:
  before_script:
    - poetry run python -m pip install --upgrade pip
    - poetry install
    - poetry run python run-ci.py download-artifacts --project-id=$UPSTREAM_PROJECT_ID --pipeline-id=$UPSTREAM_PIPELINE_ID --job-name=$UPSTREAM_JOB_NAME

.before-script/rbenv-path:
  before_script:
    - poetry run python -m pip install --upgrade pip
    - poetry install
    - export PATH=$HOME/.rbenv/versions/$RBENV_VERSION/bin:$PATH

.before-script/rbenv-path-download-artifacts:
  before_script:
    - poetry run python -m pip install --upgrade pip
    - poetry install
    - poetry run python run-ci.py download-artifacts --project-id=$UPSTREAM_PROJECT_ID --pipeline-id=$UPSTREAM_PIPELINE_ID --job-name=$UPSTREAM_JOB_NAME
    - export PATH=$HOME/.rbenv/versions/$RBENV_VERSION/bin:$PATH

#################
# Extend blocks #
#################

.release-artifacts:
  artifacts:
    paths:
      - vendor/tanker

##############
# lint stage #
##############

# Prevent the pipeline from passing unless the lint job is started manually
# There is no way to require _one of_ the manual checks job,
# it's all blocking or nothing blocks the pipeline. So we require manual lint instead

lint:
  rules:
    - !reference [.rules/mr/auto, rules]
    - !reference [.rules/push-master, rules]
  stage: lint
  extends:
    - .tags/linux
    - .before-script/rbenv-path
  variables:
    RBENV_VERSION: 2.7.5
  script:
    - poetry run python run-ci.py lint
  tags: !reference [.tags/linux, tags]

############
# profiles #
############

.profiles/linux/2.7:
  variables:
    RBENV_VERSION: 2.7.5
    TANKER_PROFILES: --profile linux-x86_64 shared no-http-backend

.profiles/linux/3.0:
  variables:
    RBENV_VERSION: 3.0.3
    TANKER_PROFILES: --profile linux-x86_64 shared no-http-backend

.profiles/linux/3.1:
  variables:
    RBENV_VERSION: 3.1.2
    TANKER_PROFILES: --profile linux-x86_64 shared no-http-backend

.profiles/macos/x86_64/2.7:
  extends:
    - .tags/macos/x86_64
  variables:
    RBENV_VERSION: 2.7.1
    TANKER_PROFILES: --profile macos-x86_64 shared no-http-backend

.profiles/macos/arm/2.7:
  extends:
    - .tags/macos/arm
  variables:
    RBENV_VERSION: 2.7.3
    TANKER_PROFILES: --profile macos-armv8 shared no-http-backend

#################
# prepare stage #
#################

.rules/prepare:
  rules:
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/mr/manual, rules]
    - !reference [.rules/deploy-pipeline, rules]

.prepare:
  stage: prepare
  extends:
    - .before-script/rbenv-path
    - .rules/prepare
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home --remote $CONAN_REMOTE prepare --use-tanker=deployed --tanker-ref $SDK_NATIVE_LATEST_CONAN_REFERENCE $TANKER_PROFILES

prepare/linux:
  extends:
    - .profiles/linux/2.7
    - .prepare
  tags: !reference [.tags/linux, tags]

prepare/macos/x86_64:
  extends:
    - .profiles/macos/x86_64/2.7
    - .prepare

prepare/macos/arm:
  extends:
    - .profiles/macos/arm/2.7
    - .prepare

###############
# check stage #
###############

.check/native-from-sources:
  stage: check
  extends:
    - .rules/native-from-sources
    - .before-script/rbenv-path
  dependencies: []
  script:
    - poetry run python run-ci.py --isolate-conan-user-home --remote $CONAN_REMOTE prepare --use-tanker=same-as-branch $TANKER_PROFILES
    - poetry run python run-ci.py --isolate-conan-user-home --remote $CONAN_REMOTE build --test

check/native-from-sources/linux/2.7:
  extends:
    - .profiles/linux/2.7
    - .check/native-from-sources
  tags: !reference [.tags/compilation-linux, tags]

check/native-from-sources/linux/3.0:
  extends:
    - .profiles/linux/3.0
    - .check/native-from-sources
  tags: !reference [.tags/compilation-linux, tags]

check/native-from-sources/linux/3.1:
  extends:
    - .profiles/linux/3.1
    - .check/native-from-sources
  tags: !reference [.tags/compilation-linux, tags]

check/native-from-sources/macos/x86_64/2.7:
  extends:
    - .profiles/macos/x86_64/2.7
    - .check/native-from-sources

check/native-from-sources/macos/arm/2.7:
  extends:
    - .profiles/macos/arm/2.7
    - .check/native-from-sources

.rules/check/deployed-native:
  rules:
    - !reference [.rules/mr/manual, rules]
    - !reference [.rules/web/auto, rules]

.check/deployed-native:
  stage: check
  extends:
    - .before-script/rbenv-path
    - .rules/check/deployed-native
  script:
    - poetry run python run-ci.py --isolate-conan-user-home --remote $CONAN_REMOTE build --test

check/deployed-native/linux/2.7:
  extends:
    - .profiles/linux/2.7
    - .check/deployed-native
  needs:
    - prepare/linux
  tags: !reference [.tags/linux, tags]

check/deployed-native/linux/3.0:
  extends:
    - .profiles/linux/3.0
    - .check/deployed-native
  needs:
    - prepare/linux
  tags: !reference [.tags/linux, tags]

check/deployed-native/linux/3.1:
  extends:
    - .profiles/linux/3.1
    - .check/deployed-native
  needs:
    - prepare/linux
  tags: !reference [.tags/linux, tags]

check/deployed-native/macos/x86_64/2.7:
  extends:
    - .profiles/macos/x86_64/2.7
    - .check/deployed-native
  needs:
    - prepare/macos/x86_64

check/deployed-native/macos/arm/2.7:
  extends:
    - .profiles/macos/arm/2.7
    - .check/deployed-native
  needs:
    - prepare/macos/arm

.check/downstream:
  stage: check
  extends:
    - .before-script/rbenv-path-download-artifacts
  dependencies: []
  script:
    - poetry run python run-ci.py --isolate-conan-user-home --remote $CONAN_REMOTE prepare --use-tanker=upstream $TANKER_PROFILES
    - poetry run python run-ci.py --isolate-conan-user-home --remote $CONAN_REMOTE build --test

check/downstream/linux/2.7:
  extends:
    - .profiles/linux/2.7
    - .check/downstream
    - .rules/check/downstream/linux
  tags: !reference [.tags/linux, tags]

check/downstream/linux/3.0:
  extends:
    - .profiles/linux/3.0
    - .check/downstream
    - .rules/check/downstream/linux
  tags: !reference [.tags/linux, tags]

check/downstream/linux/3.1:
  extends:
    - .profiles/linux/3.1
    - .check/downstream
    - .rules/check/downstream/linux
  tags: !reference [.tags/linux, tags]

check/downstream/macos/x86_64/2.7:
  extends:
    - .profiles/macos/x86_64/2.7
    - .check/downstream
    - .rules/check/downstream/macos/x86_64

check/downstream/macos/arm/2.7:
  extends:
    - .profiles/macos/arm/2.7
    - .check/downstream
    - .rules/check/downstream/macos/arm

################
# deploy stage #
################

deploy:
  stage: deploy
  extends:
    - .rules/deploy/ruby
    - .before-script/rbenv-path
  script:
    - poetry run python run-ci.py deploy --version $SDK_RUBY_RELEASE_VERSION
  needs:
    - prepare/linux
    - prepare/macos/x86_64
    - prepare/macos/arm
  variables:
    RBENV_VERSION: 3.1.2
  release:
    description: sdk-ruby v$SDK_RUBY_RELEASE_VERSION
    tag_name: v$SDK_RUBY_RELEASE_VERSION
  tags: !reference [.tags/linux, tags]
