include:
  project: TankerHQ/gitlab-ci-files
  ref: theo/fix_workflow_rules
  file: /ruby.yml

###############
# check stage #
###############

lint:
  extends:
    - .check
    - .tags/linux
    - .rules/mr/auto
    - .before-script/rbenv-path
  variables:
    RBENV_VERSION: 2.7.1
  script:
    - poetry run python run-ci.py lint

check/native-from-sources/linux/2.6:
  extends:
    - .check
    - .tags/linux
    - .check/native-from-sources/linux
  variables:
    RBENV_VERSION: 2.6.6

check/native-from-sources/linux/2.7:
  extends:
    - .check
    - .tags/linux
    - .check/native-from-sources/linux
  variables:
    RBENV_VERSION: 2.7.1

check/deployed-native/linux/2.6:
  extends:
    - .check
    - .tags/linux
    - .before-script/rbenv-path
    - .rules/deployed-native
    - .release-artifacts
  variables:
    RBENV_VERSION: 2.6.6
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref $SDK_NATIVE_LATEST_CONAN_REFERENCE --profile gcc8-release-shared

check/deployed-native/linux/2.7:
  extends:
    - .check
    - .tags/linux
    - .before-script/rbenv-path
    - .rules/deployed-native
    - .release-artifacts
  variables:
    RBENV_VERSION: 2.7.1
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref $SDK_NATIVE_LATEST_CONAN_REFERENCE --profile gcc8-release-shared

check/native-from-sources/macos/2.7:
  extends:
    - .check
    - .tags/macos
    - .rules/native-from-sources
  variables:
    RBENV_VERSION: 2.7.1
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile macos-release-shared

check/deployed-native/macos/2.7:
  extends:
    - .check
    - .tags/macos
    - .rules/deployed-native
    - .release-artifacts
  variables:
    RBENV_VERSION: 2.7.1
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref $SDK_NATIVE_LATEST_CONAN_REFERENCE --profile macos-release-shared

check/downstream/linux/2.6:
  extends:
    - .check/downstream/linux
  variables:
    RBENV_VERSION: 2.6.6

check/downstream/linux/2.7:
  extends:
    - .check/downstream/linux
  variables:
    RBENV_VERSION: 2.7.1

check/downstream/macos/2.7:
  extends:
    - .check
    - .tags/macos
    - .rules/check/downstream/macos
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile macos-release-shared
  variables:
    RBENV_VERSION: 2.7.1

################
# deploy stage #
################

deploy:
  extends:
    - .deploy
    - .tags/linux
    - .rules/deploy/ruby
    - .before-script/rbenv-path
  script:
    - poetry run python run-ci.py deploy --version $SDK_RUBY_RELEASE_VERSION
  variables:
    RBENV_VERSION: 2.6.6
  release:
    description: sdk-python v$SDK_RUBY_RELEASE_VERSION
    tag_name: v$SDK_RUBY_RELEASE_VERSION

mirror:
  extends:
    - .deploy
    - .tags/linux
    - .rules/mirror
  script:
    - poetry run python run-ci.py mirror
