AllCops:
  # We lock rubocop in Gemfile.lock, so we want all the pending cops. This means
  # you must fix all new cops when bumping rubocop in the gemfile, which seems
  # reasonable.
  # See: https://docs.rubocop.org/rubocop/versioning.html for more details
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'build/**/*'
    - 'lib/tanker-core.rb'
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 120

# This is annoying for "enum" classes like Verification
Layout/EmptyLineBetweenDefs:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/ClassAndModuleChildren:
  Enabled: false

# The %i[] syntax is not obvious to readers
Style/SymbolArray:
  EnforcedStyle: brackets

# One accessor per line is actually more readable sometimes
Style/AccessorGrouping:
  Enabled: false

# The full documentation is on our website
Style/Documentation:
  Enabled: false

# Cyclomatic complexity is not a great metric
# This gives false positives when switching on a few cases
Metrics/AbcSize:
  Enabled: false

# Tests have long blocks
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
