[version]
current = "0.0.0"

regex = '''
  (dev)
  |
    (
    (?P<major>\d+)
    \.
    (?P<minor>\d+)
    \.
    (?P<patch>\d+)
    (
      \.
      (?P<channel>alpha|beta|r)
      \.
      (?P<release>\d+)
    )?
  )
'''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[before_commit]]
name = "Update Gemfile.lock"
cmd = "bundle"


[[file]]
src = "lib/tanker/core/version.rb"
search = "VERSION = '{current_version}'"
