# frozen_string_literal: true

require 'set'
# always keep this file first, it defines the module and the class
require_relative 'core/version'
require_relative 'c_tanker'
require_relative 'error'
require_relative 'core/http'
require_relative 'core/session'
require_relative 'core/verification'
require_relative 'core/encryption'
require_relative 'core/stream'
require_relative 'sharing_options'
require_relative 'verification_options'
require_relative 'core/group'
require_relative 'core/encryption_session'
require_relative 'core/log_record'
require_relative 'core/attach_result'
require_relative 'core/init'
require 'tanker/c_tanker/fork_hook'
